### ISSUE TITLE
USER STORY: Create Post

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#1]
EPIC: Post creation

As a site user I can create a new post so that I can share it with other users

**Acceptance Criteria**

- [x] When logged in a registered user can access the post creation form
- [x] Form contains inputs for Title, description, image, opening times, location, tags, number of likes, comments publish request, request publishing and submit
- [x] Form submission saves post to database
- [x] Input errors from users are addressed with error messages

**Tasks**

- [x] Create model
- [x] Create form
- [x] Create view
- [x] Create template
- [x] Connect URLs
- [x] Process inputs
- [x] Validate
- [x] POST handle form input errors (empty input)
- [x] Test functionality
