### ISSUE TITLE
USER STORY: Account registered

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#11]
EPIC: Account Registration

As a site user my registration is confirmed so that I can access all site user features

**Acceptance criteria**

- [ ] To register an account a user must enter a username and password (email optional )
- [ ] A username should only be able to be registered once

**Tasks**

- [ ] Install Allauth library
- [ ] Create sign up / login links
- [ ] Customise html templates
- [ ] Test functionality
