### ISSUE TITLE
USER STORY: Login confirmation

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#12]
EPIC: Account Registration

As a site user when I login this is confirmed so that I can know I am logged in

**Acceptance criteria**

- [ ] A prompt is displayed when a user logs in

**Tasks**

- [ ] Create pop up display code
- [ ] Use JS to make the message disappear after a set period
- [ ] Test functionality
