### ISSUE TITLE
USER STORY: Site administration

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#14]
EPIC: Site admin

As a Site Admin I can create, read, update and delete blog posts and comments so that I can manage the content

**Acceptance criteria**

- [ ] Admin can log in  with a superuser account
- [ ] Admin can manage all posts via the superuser account
- [ ] Admin can manage all comments with via the superuser account

**Tasks**

- [ ] Complete database model for post and comment
- [ ] Create superuser 
- [ ] Develop Admin Site
- [ ] Test  functionality
- [ ]
