### ISSUE TITLE
USER STORY: View likes

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#15]
EPIC: Like/unlike

As a site user I can view the number of likes on each post so that I can see which is the most popular and feel part of a community

**Acceptance criteria**

- [x] The total number of likes should be visible on each post
- [x] A themed icon should be used to demonstrate likes

**Tasks**

- [x] Create view for likes
- [x] Update post detail template
- [x] Connect urls
- [x] Test functionality
