### ISSUE TITLE
USER STORY: Post like

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#16]
EPIC: Likes/unlike

As a site user I can like a post so that I can interact with the content and indicate if I support a cafe

**Acceptance criteria**

- [ ] A registered user can interact and like a post
- [ ] There should be a corresponding icon that is toggled on/off

**Tasks**

- [ ] Create view 
- [ ] Update post detail template
- [ ] Connect urls
- [ ] Test functionality
