### ISSUE TITLE
USER STORY: Like prompt

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#18]
EPIC: Like/unlike

As a site user when I like a post the action is confirmed so that I can know it is liked

**Acceptance criteria**

- [ ] A prompt is displayed when a user likes a post

**Tasks**

- [ ] Create pop up display code
- [ ] Use JS to make the message disappear after a set period
- [ ] Test functionality
