### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#20]
EPIC: Comments

As a site user I can view comments on a post so that I can read the discussion

**Acceptance criteria**

- [x] All comments are visible to all users
- [x] Comments are sorted by date created

**Tasks**

- [x] Complete model for comment
- [x] Create view 
- [x] Update html template for post list
- [x] Connect urls
- [x] Test functionality
