### ISSUE TITLE
USER STORY: Make comment

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#21]
EPIC: Comments

As a site user I can make a comment on a post so that I can be involved in the discussion

**Acceptance criteria**

- [ ] Only registered and logged in users can be leave comments on a post
- [ ] Name, date and comment should be displayed

**Tasks**

- [ ] Create comment form with body field
- [ ] Create view 
- [ ] Update html template for post list
- [ ] Create link to submit comment
- [ ] Connect urls
- [ ] Test functionality
