### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#22]
EPIC: Comments

As a site user I can delete my comment  so that I can be update the content

**Acceptance criteria**

- [ ] Only registered and logged in users can delete their comments on a post
- [ ] Defensive coding used to confirm when deleting

**Tasks**

- [ ] Createhtml template for delete comment
- [ ] Create view 
- [ ] Create link for delete comment
- [ ] Connect urls
- [ ] Test functionality
