### ISSUE TITLE
USER STORY: UX

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#25]
EPIC: UX/Design

As a site user I can get an overall understanding and impression of the site because user experience design, accessibility and responsivity principled are employed so that I can quickly determine the purpose of the site and continue using it

**Acceptance criteria**

- [x] Site navigation is simple, easy to use and intuitive
- [x] The site meets accessibility requirements
- [x] Style and colour choices are consistent and pleasing

**Tasks**

- [x] Create logo/brand in navigation bar on all pages
- [x] Create navigation items that are clearly labelled on all pages
- [x] Use consistent font for headings
- [x] Use consistent colour scheme on all pages
- [x] Design using accessibility requirements
- [x] Test using performance tools
- [x] Add indication of username for logged in profile to nav bar
- [x] Add tab in nav bar for 'Post Add' where a user can add a post
