### ISSUE TITLE
USER STORY: Responsivity

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#26]
EPIC: UX/Design

As a site user I can use the site on the different devices so that I can still access all functionality

- [ ] Suitable resolution for respective devices used

**Tasks**

- [ ] Use relevant media queries
- [ ] Adjust page layout on smaller devices for better UX
- [ ] Test functionality at different resolutions
