### ISSUE TITLE
USER STORY: Hero image

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#27]
EPIC: UX/Design

As a site user I am presented with a hero image so that I can identify with the content

**Acceptance criteria**

- [ ] Hero image is displayed on home page that is related to purpose of site

**Tasks**

- [ ] Use hero image that matches the aesthetic of the content
- [ ] Test appearance on different resolutions
