### ISSUE TITLE
USER STORY: Developer links

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#28]
EPIC: UX/Design

As a site user I am presented with a link to the developers other projects so that I can access more content

**Acceptance criteria**

- [ ] GitHub link included in footer 
- [ ] Link opens in separate window

**Tasks**

- [ ] Add link to footer and develop footer
