### ISSUE TITLE
USER STORY: Home page slide show

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#29]
EPIC: UX/Design

As a site user I can view a slide show of with new/recent posts so that I can easily see any new activity

**Acceptance criteria**

- [ ] User accesses slide show on home page

**Tasks**

- [ ] Add Bootstrap carousel
- [ ] Create code for min 3 cards/images
- [ ] Test functionality

**Comment by MattuW4** [comment]
Exchanged carousel for 3 images with highest number of likes due to time constraint
