### ISSUE TITLE
USER STORY: View Post

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#3]
EPIC: Post Creation

As a site user I can read the content of posts so that I can be informed and interact with the content

**Acceptance criteria**

- [x] - After submitting the post, the user is redirected to the home page 
- [x] screen where they can view the post
- [x] - Posts are sorted by date created
- [x] - Image, cafe name, location, rating and number of likes is shown on screen for each post
- [x] - Paginated view

**Tasks**

- [x] Complete database model for post and comment
- [x] Create view code
- [x] Create html template for post detail
- [x] Create link to access post detail
- [x] Connect Urls
- [x] Test functionality
