### ISSUE TITLE
USER STORY: Front end technology

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#34]
EPIC: Software technologies

As a site user I can use a front end app so that I can send and get date from a back end database

**Acceptance criteria**

- [x] Front end is interactive and provides requisite functionality to interact with backend database

**Tasks**

- [x] Django 3.2 is the LTS (Long Term Support) version
- [x] Gunicorn is the server to run Django on Heroku.
- [x] PostgreSQL and pyscopg2 libraries
- [x] Cloudinary Libraries
- [x] Create requirements file
- [x] Create Project
- [x] Create App
- [x] Create secret key
- [x] Ensure allowed hosts is updated in settings.py
- [x] Create env.py file and add database url, secret key and cloudinary url
- [x] Add App to installed apps
- [x] Migrate Changes
- [x] Add hostname to ALLOWED_HOSTS in [settings.py](http://settings.py/)
- [x]  Add Procfile
