### ISSUE TITLE
USER STORY: Back end technologies

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#35]
EPIC: Software technologies

As a site user I access a backend database so I can interact and use a frontend app

**Acceptance criteria**

- [ ] Backend database provides store that can be accessed through front end

**Tasks**

- [ ] Create new Heroku app
- [ ] Create an external database on ElephantSQL
- [ ] Create env.py file and environment variables
- [ ] Create Heroku Config Vars
- [ ] Setup Cloudinary
- [ ] Deploy to Heroku
