### ISSUE TITLE
Selecting a category

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#37]
EPIC: Categories

As a site user I can select a category for my post so that I can indicate shared features of a cafe

**Acceptance criteria**

- [ ] Only registered and logged in users can be add a category to their posts

**Tasks**

- [ ] Create model
- [ ] Create category form
- [ ] Create view 
- [ ] Update html template for post list
- [ ] Create link to submit category
- [ ] Connect urls
- [ ] Test functionality
