### ISSUE TITLE
Searching categories

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#38]
EPIC: Categories

As a site user I can search through categories of posts so that I can see related features of cafes

**Acceptance criteria**

- [ ] Registered and unregistered users can be search through categories to see related features of cafes

**Tasks**

- [ ] Create model
- [ ] Create view 
- [ ] Update html template for create view
- [ ] Create link to submit category
- [ ] Connect urls
- [ ] Test functionality
