### ISSUE TITLE
USER STORY: Build home page

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#40]
EPIC: UX/Design

As a site user I can easily understand the purpose of the site and begin to navigate to other pages using spoke approach so that the site is navigable and understandable

**Acceptance criteria**

- [ ] Develop home page with links to other areas of the site for un/registered users
- [ ] Connect to other elements like hero image, featurette etc. 

**Tasks**

- [ ] Build home page
- [ ] Embed hero image, featurette
