### ISSUE TITLE
USER STORY: Develop a base template

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#41]
EPIC: UX/Design

As a site user I can easily have familiarity with repeated features across the whole site so that navigate and access features seamlessly. 

**Acceptance criteria**

- [x] Consistent pages developed across the site that are consistent and accessible, whether a registered or unregistered user

**Tasks**

- [x] Develop base template
- [x] Include nav bar with links
- [x] Create space within the body different page content
- [x] Ensure that there are elements that can be varied based on user registration e.g. log in/log out feature
- [x] Develop footer 
- [x] Style with CSS
- [x] Test functionality
