### ISSUE TITLE
Delete post

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#5]
EPIC: Post creation

As a site user I can delete a post so that I can manage my content

**Acceptance criteria**

- [ ] - When logged in a user can delete a post that they have created
- [ ] - There is defensive programming to ensure that deletion is intended

**Tasks**

- [ ] Create view 
- [ ] Create html template 
- [ ] Create link to access delete post
- [ ] Connect Urls
- [ ] Test functionality
