### ISSUE TITLE
USER STORY: Submission prompt

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#6]
EPIC: Post Creation

As a site user when I submit a post the action is confirmed so that I can know it is posted

**Acceptance criteria**

- [x] A prompt is displayed when a user submits a post

**Tasks**

- [x] Create pop up display code
- [x] Use JS to make the message disappear after a set period
- [x] Test functionality
