### ISSUE TITLE
USER STORY: Edit confirmation

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#7]
EPIC: Post Creation

As a site user when I edit a post the action is confirmed so that I can know it is edited

**Acceptance criteria**

- [x] A prompt is displayed when a user edits a post

**Tasks**

- [x] Create pop up display code
- [x] Use JS to make the message disappear after a set period
- [x] Test functionality
