### ISSUE TITLE
Deletion confirmation

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/cafe-stop#8]
EPIC: Post Creation

As a site user when I delete a post the action is confirmed so that I know it has been deleted

**Acceptance criteria**

- [ ] A prompt is displayed when a user deletes a post

**Tasks**

- [ ] Create pop up display code
- [ ] Use JS to make the message disappear after a set period
- [ ] Test functionality
